## YAML Template.
---name: Task 2 Multi-Platform-Jobs

on:
  pull_request:
    branches: [ "main" ]

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print OS Info
        run: uname -a
      - name: Create and Display File
        run: |
          echo "This is Linux" > linux.txt
          cat linux.txt

  windows-job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print OS Info
        run: systeminfo | findstr /B /C:"OS Name"
      - name: Create and Display File
        run: |
          echo "This is Windows" > windows.txt
          type windows.txt

  macos-job:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print OS Info
        run: uname -a
      - name: Create and Display File
        run: |
          echo "This is MacOS" > macos.txt
          cat macos.txt
